version: '2'
services:
  postgres_god:
    image: kartoza/postgis:9.6-2.4
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 6432:5432

  god_service:
    build: ./
    volumes:
      - .:/code
    links:
      - postgres_god
    ports:
      - 9888:80
    environment:
      PORT: 80
      PG_CONNECTION: postgres://postgres:secret@postgres_god:5432/
      API_KEY: 'API_PASSWORD'
    networks: 
      - default
    depends_on:
      - postgres_god

volumes:
  postgres_data: